defaults: # import plotting configuration
  - wp_eff_var@_global_: ???
  - _self_

vs_type: jet
pred_samples: # factorised from create_df() args for partial calls per tau_type
  tau:
    # STAU_M400_100mm-new-ntuples_train_sample: 
    # AN-2024-HeavyNeutrino_trilepton_M-10_V-0.0004_tau_massiveAndCKM_LO:
    # AN-2024-STAU_M400_100mm:
    stau400_lsp1_ctau1000mm:
      filename_pattern: '*_pred.h5' # single files, list of files and "*" are supported 
      sample_lumi: null
      reweight_to_lumi: null # null to not reweight
  jet:
    # TTToSemiLeptonic-new-ntuples-plus-PU:
    # STAU_M400_100mm-new-ntuples:
    # HeavyNeutrino_trilepton_M-10_V-0.0004_tau_massiveAndCKM_LO:
    # TTToSemiLeptonic-new-ntuples:
    AN-2024-TTToSemiLeptonic:
      filename_pattern: '*_pred.h5'
      sample_lumi: null
      reweight_to_lumi: null


require_WPs_in_numerator: False # whether to require passing of `WPs_to_require` (all except the one for `vs_type`) in the numerator of the efficiency formula
require_WPs_in_denominator: False # whether to require passing of `WPs_to_require` (all except the one for `vs_type`) in the denominator of the efficiency formula
WPs_to_require:
  e: VVVLoose
  mu: VLoose
  jet: VVVLoose

WPs_to_plot: 
  [
     "Loose",
     "Medium",
     "Tight",
     "VTight",
     "VVTight"
  ]
    

from_skims: False # if False, will run create_df() and log the skims to mlflow artifacts (in `output_skim_folder`), otherwise will read the skims  
output_skim_folder: wp_eff/data # as /path/within/mlflow/artifacts/, to read/write skim from
create_df: # dataframe composition
  _target_: functools.partial # to instantiate a partial create_df() object 
  _args_: ["${get_method:__main__.create_df}"]

  # path to prediction files
  path_to_mlflow: ???
  experiment_id: ???
  run_id: ???
  path_to_preds: "${create_df.path_to_mlflow}/${create_df.experiment_id}/${create_df.run_id}/artifacts/predictions/"
  
  # naming conventions of prediction files
  pred_group_name: predictions
  pred_column_prefix: node_ # node_ // pred_
  target_group_name: targets # targets // labels
  target_column_prefix: node_ # node_ // label_

  # add columns to apply selection on
  # paths to input ROOT files will be retrieved from corresponding pred_input_filemap.json
  add_columns_from: 'predictions' # either "predictions" or "inputs"
  # add_columns: [ 'jet_pt', 'jet_eta', 'jet_phi']
  # group_or_tree_name: taus # add_columns // taus -- either group name (add_columns_from=prediction) or tree name (add_columns_from=inputs)
  # selection: '(tau_pt>=20) and (tau_pt<1000) and (abs(tau_eta) < 2.3) and (abs(tau_dz) < 0.2) and not (tau_decayMode in [5,6])'
  # selection: "abs(jet_eta) > 1.5 and abs(jet_eta) < 2.3 and (jet_pt > 20)"
  # selection: "abs(jet_eta) < 1.5 and (jet_pt > 20)"
  selection: "abs(jet_eta) < 2.3 and (jet_pt > 20)"
  # add_columns: [ 'jet_pt', 'jet_eta', 'Lrel', 'Lxy', 'nConstituents']
  add_columns: [ 'jet_pt', 'jet_eta', 'Lrel', 'Lxy']
  group_or_tree_name: global_vars

output_filename: wp_eff/define_WP/vs_${vs_type}/${var_cfg.var_name}.png # as /path/within/mlflow/artifacts/filename.png