# basic imports
defaults:
  - discriminator: ???
  - selection
  - _self_

# mflow run info
path_to_mlflow: ???
experiment_id: ???
run_id: ???

# phase space region
vs_type: ??? # jet/e/mu
dataset_alias: ??? # alias to reference a mixture of input_samples below, e.g. tau_DY_jet_TT
bins:
  jet_pt: [[20, 1000], [20, 50], [50, 100], [100, 1000]]
  jet_eta: [[-2.3, 2.3]]
  Lrel: [
          [0.0, 200.0],
          [0.0, 1.0],
          [1.0, 5.0],
          [5.0, 20.0],
          [20.0, 50.0],
          [50.0, 200.0]
        ]
# dm_bins: [[0, 1, 2, 10, 11]]

# selection
input_branches: [ 'tau_pt', 'tau_eta', 'tau_decayMode' , 'tau_dz'] # add here WP branches if necessary
global_branches: [ 'jet_pt', 'jet_eta', 'Lxy', 'Lz', 'Lrel' ]
cuts: "abs(jet_eta) < 2.3 and (jet_pt > 20)" 
WPs_to_require: null # null to not apply WP as selection
# WPs_to_require: ### example for vs. jet
#   e: VVVLoose
#   mu: VLoose

# inputs/paths
input_samples: ??? # "sample_alias": [list of strings with tau types to be selected]
  # stau250_lsp1_ctau100mm: ['tau']
  # TTToSemiLeptonic-new-ntuples: ['jet']

  # STAU_M400_100mm-new-ntuples: ['tau']
  # STAU_M400_100mm-new-ntuples_train_sample: ['tau']
  # HeavyNeutrino_trilepton_M-10_V-0.0004_tau_massiveAndCKM_LO: ['tau']
  # TTToSemiLeptonic-new-ntuples: ['jet']
  # TTToSemiLeptonic-new-ntuples-plus-PU : ['jet']

path_to_input: null
path_to_pred: '${path_to_mlflow}/${experiment_id}/${run_id}/artifacts/predictions/{sample_alias}/*_pred.h5'
path_to_target: '${path_to_mlflow}/${experiment_id}/${run_id}/artifacts/predictions/{sample_alias}/*_pred.h5'
path_to_weights_taus: null
path_to_weights_vs_type: null

# misc.
roc_prune_decimal: # precision on TPR rounding 
  e: 3
  mu: 4
  jet: 3
