var_cfg:
  _target_: functools.partial
  _args_: ["${get_method:__main__.plot_efficiency}"]

  var_name: jet_pt
  var_bins: [ 20, 30, 40, 50, 60, 70, 100, 120, 1000 ]

  xlabels: null 
  xerr: null

  xscale: log
  yscale_1: linear
  yscale_2: log

  ylim_1: [0.1, 1]
  ylim_2: [5e-7, 1.0]

  xtitle: "$p_{T}$ (GeV)"
  ytitle_1: Tau ID efficiency
  ytitle_2: "${vs_type} mis-id probability"
  legend_loc: "lower right"